language: objective-c
osx_image: xcode8.3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - osx_image: xcode8.3
      env: R_SDK=iphonesimulator8.3 R_OS_VER=8.3 R_NAME="iPhone 5s"
    - osx_image: xcode8.3
      env: R_SDK=iphonesimulator10.3 R_OS_VER=10.3 R_NAME="iPhone 6s"

script:
 -   xctool -project PMDCollections.xcodeproj -scheme PMDCollectionsTests -sdk $R_SDK -destination platform='iOS Simulator, OS=$R_OS_VER,name=$R_NAME' -configuration DEBUG test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES