language: objective-c
osx_image: xcode8.2
xcode_project: PMDCollections.xcodeproj

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
 -   xctool -scheme PMDCollectionsTests -sdk iphonesimulator10.3 -destination platform='iOS Simulator, OS=10.3 ,name='iPhone 7' -configuration DEBUG test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
